<?php
function FunXmlTOmysql($xmlstring,$cname){
include "conn.php";
//$MASTERID1=0;
set_time_limit(400);

$file = 'err.txt';
		// Open the file to get existing content
		$current = file_get_contents($file);

if (!$conn) {
    die("Connection failed: " . mysqli_connect_error());
}
 

		
$x=simplexml_load_string($xmlstring);
  $i=0;//echo "cr";
  foreach($x->BODY as $v){
		   foreach($v->DATA as $c)
           { 
              foreach($c->COLLECTION as $e) 
			  {		
                foreach($e->VOUCHER as $vno)
				{				ECHO "============="."<BR>";
					  //echo $vo->DATE."-".$i++."<br/>";
					  foreach($vno->ALLINVENTORYENTRIES as $inv)
				  {
					  		 
$GUID1=$vno->GUID;
$DATE1 =  $vno->DATE ; 
//$mt = $DATE1 
$mt=$DATE1;//date_format(date() ,"F-Y");
$VATDEALERTYPE1=$vno->VATDEALERTYPE;
$PARTYNAME1=$vno->PARTYNAME;
$VOUCHERTYPENAME1=$vno->VOUCHERTYPENAME;
$VOUCHERTYPENAME1=str_replace("'","",$VOUCHERTYPENAME1);
$REFERENCE1=$vno->REFERENCE;
$VOUCHERNUMBER1=$vno->VOUCHERNUMBER;
$PARTYLEDGERNAME1=$vno->PARTYLEDGERNAME;
$BASICBASEPARTYNAME1=$vno->BASICBASEPARTYNAME;
$CSTFORMISSUETYPE1=$vno->CSTFORMISSUETYPE;
$CSTFORMRECVTYPE1=$vno->CSTFORMRECVTYPE;
$FBTPAYMENTTYPE1=$vno->FBTPAYMENTTYPE;
$PERSISTEDVIEW1=$vno->PERSISTEDVIEW;

$BASICBUYERNAME1=$vno->BASICBUYERNAME;
//str_replace("'","",$BASICBUYERNAME1);
$BASICBUYERNAME1=""; 


$BASICDATETIMEOFINVOICE1=$vno->BASICDATETIMEOFINVOICE;
$BASICDATETIMEOFREMOVAL1=$vno->BASICDATETIMEOFREMOVAL;
$VCHGSTCLASS1=$vno->VCHGSTCLASS;
$DIFFACTUALQTY1=$vno->DIFFACTUALQTY;
$ISMSTFROMSYNC1=$vno->ISMSTFROMSYNC;
$ASORIGINAL1=$vno->ASORIGINAL;
$AUDITED1=$vno->AUDITED;
$FORJOBCOSTING1=$vno->FORJOBCOSTING;
$ISOPTIONAL1=$vno->ISOPTIONAL;
$EFFECTIVEDATE1=$vno->EFFECTIVEDATE;
$USEFOREXCISE1=$vno->USEFOREXCISE;
$ISFORJOBWORKIN1=$vno->ISFORJOBWORKIN;
$ALLOWCONSUMPTION1=$vno->ALLOWCONSUMPTION;
$USEFORINTEREST1=$vno->USEFORINTEREST;
$USEFORGAINLOSS1=$vno->USEFORGAINLOSS;
$USEFORGODOWNTRANSFER1=$vno->USEFORGODOWNTRANSFER;
$USEFORCOMPOUND1=$vno->USEFORCOMPOUND;
$USEFORSERVICETAX1=$vno->USEFORSERVICETAX;
$ISEXCISEVOUCHER1=$vno->ISEXCISEVOUCHER;
$EXCISETAXOVERRIDE1=$vno->EXCISETAXOVERRIDE;
$USEFORTAXUNITTRANSFER1=$vno->USEFORTAXUNITTRANSFER;
$EXCISEOPENING1=$vno->EXCISEOPENING;
$USEFORFINALPRODUCTION1=$vno->USEFORFINALPRODUCTION;
$ISTDSOVERRIDDEN1=$vno->ISTDSOVERRIDDEN;
$ISTCSOVERRIDDEN1=$vno->ISTCSOVERRIDDEN;
$ISTDSTCSCASHVCH1=$vno->ISTDSTCSCASHVCH;
$INCLUDEADVPYMTVCH1=$vno->INCLUDEADVPYMTVCH;
$ISSUBWORKSCONTRACT1=$vno->ISSUBWORKSCONTRACT;
$ISVATOVERRIDDEN1=$vno->ISVATOVERRIDDEN;
$IGNOREORIGVCHDATE1=$vno->IGNOREORIGVCHDATE;
$ISSERVICETAXOVERRIDDEN1=$vno->ISSERVICETAXOVERRIDDEN;
$ISISDVOUCHER1=$vno->ISISDVOUCHER;
$ISEXCISEOVERRIDDEN1=$vno->ISEXCISEOVERRIDDEN;
$ISEXCISESUPPLYVCH1=$vno->ISEXCISESUPPLYVCH;
$ISVATPRINCIPALACCOUNT1=$vno->ISVATPRINCIPALACCOUNT;
$ISSHIPPINGWITHINSTATE1=$vno->ISSHIPPINGWITHINSTATE;
$ISCANCELLED1=$vno->ISCANCELLED;
$HASCASHFLOW1=$vno->HASCASHFLOW;
$ISPOSTDATED1=$vno->ISPOSTDATED;
$USETRACKINGNUMBER1=$vno->USETRACKINGNUMBER;
$ISINVOICE1=$vno->ISINVOICE;
$MFGJOURNAL1=$vno->MFGJOURNAL;
$HASDISCOUNTS1=$vno->HASDISCOUNTS;
$ASPAYSLIP1=$vno->ASPAYSLIP;
$ISCOSTCENTRE1=$vno->ISCOSTCENTRE;
$ISSTXNONREALIZEDVCH1=$vno->ISSTXNONREALIZEDVCH;
$ISEXCISEMANUFACTURERON1=$vno->ISEXCISEMANUFACTURERON;
$ISBLANKCHEQUE1=$vno->ISBLANKCHEQUE;
$ISVOID1=$vno->ISVOID;
$ISONHOLD1=$vno->ISONHOLD;
$ORDERLINESTATUS1=$vno->ORDERLINESTATUS;
$VATISAGNSTCANCSALES1=$vno->VATISAGNSTCANCSALES;
$VATISPURCEXEMPTED1=$vno->VATISPURCEXEMPTED;
$ISVATRESTAXINVOICE1=$vno->ISVATRESTAXINVOICE;
$ISDELETED1=$vno->ISDELETED;
$CHANGEVCHMODE1=$vno->CHANGEVCHMODE;
$ALTERID1=$vno->ALTERID;
$MASTERID1=$vno->MASTERID;
$VOUCHERKEY1=$vno->VOUCHERKEY;
$EXCLUDEDTAXATIONS_LIST1=$vno->EXCLUDEDTAXATIONS_LIST;
$OLDAUDITENTRIES_LIST1=$vno->OLDAUDITENTRIES_LIST;
$ACCOUNTAUDITENTRIES_LIST1=$vno->ACCOUNTAUDITENTRIES_LIST;
$AUDITENTRIES_LIST1=$vno->AUDITENTRIES_LIST;
$DUTYHEADDETAILS_LIST1=$vno->DUTYHEADDETAILS_LIST;
$SUPPLEMENTARYDUTYHEADDETAILS_LIST1=$vno->SUPPLEMENTARYDUTYHEADDETAILS_LIST;
$INVOICEDELNOTES_LIST1=$vno->INVOICEDELNOTES_LIST;
$INVOICEORDERLIST_LIST1=$vno->INVOICEORDERLIST_LIST;
$INVOICEINDENTLIST_LIST1=$vno->INVOICEINDENTLIST_LIST;
$ATTENDANCEENTRIES_LIST1=$vno->ATTENDANCEENTRIES_LIST;
$ORIGINVOICEDETAILS_LIST1=$vno->ORIGINVOICEDETAILS_LIST;
$INVOICEEXPORTLIST_LIST1=$vno->INVOICEEXPORTLIST_LIST;
$PAYROLLMODEOFPAYMENT_LIST1=$vno->PAYROLLMODEOFPAYMENT_LIST;
$ATTDRECORDS_LIST1=$vno->ATTDRECORDS_LIST;
$STOCKITEMNAME1=$inv->STOCKITEMNAME;
$STOCKITEMNAME1=str_replace($STOCKITEMNAME1,"'","");
$ISDEEMEDPOSITIVE1=$inv->ISDEEMEDPOSITIVE;
$ISLASTDEEMEDPOSITIVE1=$inv->ISLASTDEEMEDPOSITIVE;
$ISAUTONEGATE1=$inv->ISAUTONEGATE;
$ISCUSTOMSCLEARANCE1=$inv->ISCUSTOMSCLEARANCE;
$ISTRACKCOMPONENT1=$inv->ISTRACKCOMPONENT;
$ISTRACKPRODUCTION1=$inv->ISTRACKPRODUCTION;
$ISPRIMARYITEM1=$inv->ISPRIMARYITEM;
$ISSCRAP1=$inv->ISSCRAP;
$RATE1=$inv->RATE;
$s=strpos($RATE1,"/");
$UNIT1=substr($RATE1,$s+1,20);
//$RATE1=substr($RATE1,1,$s-1);
$RATE1=str_replace("/Nos","",$RATE1);
$AMOUNT1=$inv->AMOUNT;
$ACTUALQTY1=$inv->ACTUALQTY;
$ACTUALQTY1=str_replace("Nos","",$ACTUALQTY1);
//echo $ACTUALQTY1;
$BILLEDQTY1=$inv->BILLEDQTY;

 

//$sql = "INSERT INTO xml_file (DATE1,GUID,REQUESTORRULE,VOUCHERTYPENAME,VOUCHERNUMBER,PARTYLEDGERNAME,SERIALMASTER,ARESERIALMASTE,PERSISTEDVIEW,ASORIGINAL,ISINVOICE,ASPAYSLIP,ISDELETED,MASTERID,VOUCHERKEY )
 //         VALUES ('$vdate1','$guid1','$vres1','$vtype1','$vno1','$vpar1','$ser1','$vare1','$vper1','$aso1','$visi','$vasp1','$visd1','$vmas1','$vou1')";
$sql = "INSERT INTO VOUCHER (CNAME,GUID,DATE,VATDEALERTYPE,PARTYNAME,VOUCHERTYPENAME,REFERENCE,VOUCHERNUMBER,PARTYLEDGERNAME,BASICBASEPARTYNAME,CSTFORMISSUETYPE,CSTFORMRECVTYPE,FBTPAYMENTTYPE,PERSISTEDVIEW,BASICBUYERNAME,BASICDATETIMEOFINVOICE,BASICDATETIMEOFREMOVAL,VCHGSTCLASS,DIFFACTUALQTY,ISMSTFROMSYNC,ASORIGINAL,AUDITED,FORJOBCOSTING,ISOPTIONAL,EFFECTIVEDATE,USEFOREXCISE,ISFORJOBWORKIN,ALLOWCONSUMPTION,USEFORINTEREST,USEFORGAINLOSS,USEFORGODOWNTRANSFER,USEFORCOMPOUND,USEFORSERVICETAX,ISEXCISEVOUCHER,EXCISETAXOVERRIDE,USEFORTAXUNITTRANSFER,EXCISEOPENING,USEFORFINALPRODUCTION,ISTDSOVERRIDDEN,ISTCSOVERRIDDEN,ISTDSTCSCASHVCH,INCLUDEADVPYMTVCH,ISSUBWORKSCONTRACT,ISVATOVERRIDDEN,IGNOREORIGVCHDATE,ISSERVICETAXOVERRIDDEN,ISISDVOUCHER,ISEXCISEOVERRIDDEN,ISEXCISESUPPLYVCH,ISVATPRINCIPALACCOUNT,ISSHIPPINGWITHINSTATE,ISCANCELLED,HASCASHFLOW,ISPOSTDATED,USETRACKINGNUMBER,ISINVOICE,MFGJOURNAL,HASDISCOUNTS,ASPAYSLIP,ISCOSTCENTRE,ISSTXNONREALIZEDVCH,ISEXCISEMANUFACTURERON,ISBLANKCHEQUE,ISVOID,ISONHOLD,ORDERLINESTATUS,VATISAGNSTCANCSALES,VATISPURCEXEMPTED,ISVATRESTAXINVOICE,ISDELETED,CHANGEVCHMODE,ALTERID,MASTERID,VOUCHERKEY,EXCLUDEDTAXATIONS_LIST,OLDAUDITENTRIES_LIST,ACCOUNTAUDITENTRIES_LIST,AUDITENTRIES_LIST,DUTYHEADDETAILS_LIST,SUPPLEMENTARYDUTYHEADDETAILS_LIST,INVOICEDELNOTES_LIST,INVOICEORDERLIST_LIST,INVOICEINDENTLIST_LIST,ATTENDANCEENTRIES_LIST,ORIGINVOICEDETAILS_LIST,INVOICEEXPORTLIST_LIST,PAYROLLMODEOFPAYMENT_LIST,ATTDRECORDS_LIST,STOCKITEMNAME,ISDEEMEDPOSITIVE,ISLASTDEEMEDPOSITIVE,ISAUTONEGATE,ISCUSTOMSCLEARANCE,ISTRACKCOMPONENT,ISTRACKPRODUCTION,ISPRIMARYITEM,ISSCRAP,RATE,AMOUNT,ACTUALQTY,BILLEDQTY,UNIT) 
VALUES ('$cname', '$GUID1','$DATE1','$VATDEALERTYPE1','$PARTYNAME1','$VOUCHERTYPENAME1','$REFERENCE1','$VOUCHERNUMBER1','$PARTYLEDGERNAME1','$BASICBASEPARTYNAME1','$CSTFORMISSUETYPE1','$CSTFORMRECVTYPE1','$FBTPAYMENTTYPE1','$PERSISTEDVIEW1','$BASICBUYERNAME1','$BASICDATETIMEOFINVOICE1','$BASICDATETIMEOFREMOVAL1','$VCHGSTCLASS1','$DIFFACTUALQTY1','$ISMSTFROMSYNC1','$ASORIGINAL1','$AUDITED1','$FORJOBCOSTING1','$ISOPTIONAL1','$EFFECTIVEDATE1','$USEFOREXCISE1','$ISFORJOBWORKIN1','$ALLOWCONSUMPTION1','$USEFORINTEREST1','$USEFORGAINLOSS1','$USEFORGODOWNTRANSFER1','$USEFORCOMPOUND1','$USEFORSERVICETAX1','$ISEXCISEVOUCHER1','$EXCISETAXOVERRIDE1','$USEFORTAXUNITTRANSFER1','$EXCISEOPENING1','$USEFORFINALPRODUCTION1','$ISTDSOVERRIDDEN1','$ISTCSOVERRIDDEN1','$ISTDSTCSCASHVCH1','$INCLUDEADVPYMTVCH1','$ISSUBWORKSCONTRACT1','$ISVATOVERRIDDEN1','$IGNOREORIGVCHDATE1','$ISSERVICETAXOVERRIDDEN1','$ISISDVOUCHER1','$ISEXCISEOVERRIDDEN1','$ISEXCISESUPPLYVCH1','$ISVATPRINCIPALACCOUNT1','$ISSHIPPINGWITHINSTATE1','$ISCANCELLED1','$HASCASHFLOW1','$ISPOSTDATED1','$USETRACKINGNUMBER1','$ISINVOICE1','$MFGJOURNAL1','$HASDISCOUNTS1','$ASPAYSLIP1','$ISCOSTCENTRE1','$ISSTXNONREALIZEDVCH1','$ISEXCISEMANUFACTURERON1','$ISBLANKCHEQUE1','$ISVOID1','$ISONHOLD1','$ORDERLINESTATUS1','$VATISAGNSTCANCSALES1','$VATISPURCEXEMPTED1','$ISVATRESTAXINVOICE1','$ISDELETED1','$CHANGEVCHMODE1','$ALTERID1','$MASTERID1','$VOUCHERKEY1','$EXCLUDEDTAXATIONS_LIST1','$OLDAUDITENTRIES_LIST1','$ACCOUNTAUDITENTRIES_LIST1','$AUDITENTRIES_LIST1','$DUTYHEADDETAILS_LIST1','$SUPPLEMENTARYDUTYHEADDETAILS_LIST1','$INVOICEDELNOTES_LIST1','$INVOICEORDERLIST_LIST1','$INVOICEINDENTLIST_LIST1','$ATTENDANCEENTRIES_LIST1','$ORIGINVOICEDETAILS_LIST1','$INVOICEEXPORTLIST_LIST1','$PAYROLLMODEOFPAYMENT_LIST1','$ATTDRECORDS_LIST1','$STOCKITEMNAME1','$ISDEEMEDPOSITIVE1','$ISLASTDEEMEDPOSITIVE1','$ISAUTONEGATE1','$ISCUSTOMSCLEARANCE1','$ISTRACKCOMPONENT1','$ISTRACKPRODUCTION1','$ISPRIMARYITEM1','$ISSCRAP1','$RATE1','$AMOUNT1','$ACTUALQTY1','$BILLEDQTY1','$UNIT1')";


//ECHO $sql;


if (mysqli_query($conn, $sql)) {
         //echo "New record created successfully.<br>";
		 ECHO   $MASTERID1 .":". $VOUCHERNUMBER1 .":". $DATE1.":". $cname ."<br>" ;


      }
	  else {
		  echo $er="Error: " . $sql . "<br>" . mysqli_error($conn) . "</BR>" ;
		   
		 
		// Append a new person to the file
		$current .= date('Y-m-d H:i:s')."\n".$er."\n";
		echo "\n";
		// Write the contents back to the file
		file_put_contents($file, $current);
        
      }		 

	}	  
		  

						  
					  }
				}				  
		     }
		  }
 	
		
  	mysqli_close($conn);
	echo $var="<br>.ok.$cname.<br>";//return $z="ok";
	//return $MASTERID1;
	//echo $MASTERID1."a=>".$mt;	
		$current .= "===============".date('Y-m-d H:i:s')."\n".$var."\n";
		 
		// Write the contents back to the file
		file_put_contents($file, $current);

  }
?>